%%% This output was generated by the following command:
%%% candc/bin/boxer --stdin --box true --resolve true --instantiate true --roles proto 

:- multifile     sem/3, id/2.
:- discontiguous sem/3, id/2.
:- dynamic       sem/3, id/2.
%%% List all movies starring Johnny Depp . 
id(1,1).
sem(1,[1001:[tok:'List',pos:'VB',lemma:list,namex:'O'],1002:[tok:all,pos:'DT',lemma:all,namex:'O'],1003:[tok:movies,pos:'NNS',lemma:movie,namex:'O'],1004:[tok:starring,pos:'VBG',lemma:star,namex:'O'],1005:[tok:'Johnny',pos:'NNP',lemma:'Johnny',namex:'I-PER'],1006:[tok:'Depp',pos:'NNP',lemma:'Depp',namex:'I-PER'],1007:[tok:'.',pos:'.',lemma:'.',namex:'O']],alfa(top,drs([[]:x0],[[1005,1006]:named(x0,johnny_depp,per,0)]),drs([[]:x1],[[]:imp(drs([[1002]:x2],[[1003]:pred(x2,movie,n,0)]),drs([[]:x3,[]:x4],[[]:rel(x3,x0,patient,0),[]:rel(x3,x2,agent,0),[1004]:pred(x3,star,v,0),[]:rel(x4,x2,patient,0),[]:rel(x4,x1,agent,0),[1001]:pred(x4,list,v,0)])),[]:pred(x1,thing,n,12)]))).
%%%   _________________________   ______________________________  
%%%  |x0                       | |x1                            | 
%%%  |.........................| |..............................| 
%%% (|named(x0,johnny_depp,per)|A|  _________   ______________  |)
%%%  |_________________________| | |x2       | |x3 x4         | | 
%%%                              | |.........| |..............| | 
%%%                              | |movie(x2)|>|patient(x3,x0)| | 
%%%                              | |_________| |agent(x3,x2)  | | 
%%%                              |             |star(x3)      | | 
%%%                              |             |patient(x4,x2)| | 
%%%                              |             |agent(x4,x1)  | | 
%%%                              |             |list(x4)      | | 
%%%                              |             |______________| | 
%%%                              |thing(x1)                     | 
%%%                              |______________________________| 


