%%% This output was generated by the following command:
%%% candc/bin/boxer --stdin --box true --resolve true --instantiate true --roles proto 

:- multifile     sem/3, id/2.
:- discontiguous sem/3, id/2.
:- dynamic       sem/3, id/2.
%%% List all countries in Europe . 
id(1,1).
sem(1,
	[
		1001:[tok:'List',pos:'NNP',lemma:'List',namex:'O'],
		1002:[tok:all,pos:'DT',lemma:all,namex:'O'],
		1003:[tok:countries,pos:'NNS',lemma:country,namex:'O'],
		1004:[tok:in,pos:'IN',lemma:in,namex:'O'],
		1005:[tok:'Europe',pos:'NNP',lemma:'Europe',namex:'I-LOC'],
		1006:[tok:'.',pos:'.',lemma:'.',namex:'O']
	],
	alfa(
		top,
		drs(
			[[]:x0],
			[
				[1005]:named(x0,europe,loc,0)
			]
		),
		drs(
			[],
			[
				[]:imp(
					drs(
						[[1002]:x1],
						[
							[1003]:pred(x1,country,n,0)
						]
					),
					drs(
						[],
						[
							[]:pred(x1,topic,a,1),
							[1001]:named(x1,list,nam,0),
							[1004]:rel(x1,x0,in,0)
						]
					)
				)
			]
		)
	)
).

%%%   ____________________   ____________________________________  
%%%  |x0                  | |                                    | 
%%%  |....................| |....................................| 
%%% (|named(x0,europe,loc)|A|  ___________   __________________  |)
%%%  |____________________| | |x1         | |                  | | 
%%%                         | |...........| |..................| | 
%%%                         | |country(x1)|>|topic(x1)         | | 
%%%                         | |___________| |named(x1,list,nam)| | 
%%%                         |               |in(x1,x0)         | | 
%%%                         |               |__________________| | 
%%%                         |____________________________________| 


