%%% This output was generated by the following command:
%%% candc/bin/boxer --stdin --box true --resolve true --instantiate true --roles proto 

:- multifile     sem/3, id/2.
:- discontiguous sem/3, id/2.
:- dynamic       sem/3, id/2.
%%% List all actors that played in a movie with Kevin Bacon . 
id(1,1).
sem(1,
	[
		1001:[tok:'List',pos:'NNP',lemma:'List',namex:'O'],
		1002:[tok:all,pos:'DT',lemma:all,namex:'O'],
		1003:[tok:actors,pos:'NNS',lemma:actor,namex:'O'],
		1004:[tok:that,pos:'WDT',lemma:that,namex:'O'],
		1005:[tok:played,pos:'VBD',lemma:play,namex:'O'],
		1006:[tok:in,pos:'IN',lemma:in,namex:'O'],
		1007:[tok:a,pos:'DT',lemma:a,namex:'O'],
		1008:[tok:movie,pos:'NN',lemma:movie,namex:'O'],
		1009:[tok:with,pos:'IN',lemma:with,namex:'O'],
		1010:[tok:'Kevin',pos:'NNP',lemma:'Kevin',namex:'I-PER'],
		1011:[tok:'Bacon',pos:'NNP',lemma:'Bacon',namex:'I-PER'],
		1012:[tok:'.',pos:'.',lemma:'.',namex:'O']
	],
	alfa(
		top,
		drs(
			[[]:x0],
			[
				[1010,1011]:named(x0,kevin_bacon,per,0)
			]
		),
		drs(
			[[]:x1,[1007]:x2,[]:x3,[1004]:x4],
			[
				[1003]:pred(x1,actor,n,0),
				[1002]:pred(x1,all,a,0),
				[1001]:named(x1,list,nam,0),
				[1008]:pred(x2,movie,n,0),
				[]:rel(x3,x4,agent,0),
				[1005]:pred(x3,play,v,0),
				[]:eq(x1,x4),
				[1006]:rel(x3,x2,in,0),
				[1009]:rel(x2,x0,with,0),
				[]:pred(x1,topic,a,1)
			]
		)
	)
).

%%%   _________________________   __________________  
%%%  |x0                       | |x1 x2 x3 x4       | 
%%%  |.........................| |..................| 
%%% (|named(x0,kevin_bacon,per)|A|actor(x1)         |)
%%%  |_________________________| |all(x1)           | 
%%%                              |named(x1,list,nam)| 
%%%                              |movie(x2)         | 
%%%                              |agent(x3,x4)      | 
%%%                              |play(x3)          | 
%%%                              |x1 = x4           | 
%%%                              |in(x3,x2)         | 
%%%                              |with(x2,x0)       | 
%%%                              |topic(x1)         | 
%%%                              |__________________| 


