%%% This output was generated by the following command:
%%% candc/bin/boxer --stdin --box true --resolve true --instantiate true --roles proto 

:- multifile     sem/3, id/2.
:- discontiguous sem/3, id/2.
:- dynamic       sem/3, id/2.
%%% Name all german film directors . 
id(1,1).
sem(1,
	[
		1001:[tok:'Name',pos:'NNP',lemma:'Name',namex:'O'],
		1002:[tok:all,pos:'DT',lemma:all,namex:'O'],
		1003:[tok:german,pos:'NN',lemma:german,namex:'O'],
		1004:[tok:film,pos:'NN',lemma:film,namex:'O'],
		1005:[tok:directors,pos:'NNS',lemma:director,namex:'O'],
		1006:[tok:'.',pos:'.',lemma:'.',namex:'O']
	],
	drs(
		[],
		[
			[]:imp(
				drs(
					[[]:x0,[]:x1,[1002]:x2],
					[
						[1005]:pred(x2,director,n,0),
						[]:rel(x2,x0,of,0),
						[1004]:pred(x0,film,n,0),
						[]:rel(x2,x1,of,0),
						[1003]:pred(x1,german,n,0)
					]
				),
				drs(
					[],
					[
						[]:pred(x2,topic,a,1),
						[1001]:named(x2,name,nam,0)
					]
				)
			)
		]
	)
).

%%%  _____________________________________ 
%%% |                                     |
%%% |.....................................|
%%% |  ____________   __________________  |
%%% | |x0 x1 x2    | |                  | |
%%% | |............| |..................| |
%%% | |director(x2)|>|topic(x2)         | |
%%% | |of(x2,x0)   | |named(x2,name,nam)| |
%%% | |film(x0)    | |__________________| |
%%% | |of(x2,x1)   |                      |
%%% | |german(x1)  |                      |
%%% | |____________|                      |
%%% |_____________________________________|


