%%% This output was generated by the following command:
%%% candc/bin/boxer --stdin --box true --resolve true --instantiate true --roles proto 

:- multifile     sem/3, id/2.
:- discontiguous sem/3, id/2.
:- dynamic       sem/3, id/2.
%%% When was Apple founded ? 
id(1,1).
sem(1,
	[
		1001:[tok:'When',pos:'WRB',lemma:when,namex:'O'],
		1002:[tok:was,pos:'VBD',lemma:be,namex:'O'],
		1003:[tok:'Apple',pos:'NNP',lemma:'Apple',namex:'O'],
		1004:[tok:founded,pos:'VBN',lemma:found,namex:'O'],
		1005:[tok: ?,pos:'.',lemma: ?,namex:'O']
	],
	alfa(
		top,
		drs(
			[[]:x0],
			[
				[1003]:named(x0,apple,nam,0)
			]
		),
		drs(
			[],
			[
				[]:whq(
					[tim:any],
					drs(
						[[]:x1],
						[
							[1001]:pred(x1,unit_of_time,n,1)
						]
					),
					x1,
					drs(
						[[]:x2],
						[
							[]:rel(x2,x1,temp_rel,0),
							[]:rel(x2,x0,patient,0),
							[1004]:pred(x2,found,v,0)
						]
					)
				)
			]
		)
	)
).
%%%   ___________________   ______________________________________  
%%%  |x0                 | |                                      | 
%%%  |...................| |......................................| 
%%% (|named(x0,apple,nam)|A|  ________________   _______________  |)
%%%  |___________________| | |x1              | |x2             | | 
%%%                        | |................| |...............| | 
%%%                        | |unit_of_time(x1)|?|temp_rel(x2,x1)| | 
%%%                        | |________________| |patient(x2,x0) | | 
%%%                        |                    |found(x2)      | | 
%%%                        |                    |_______________| | 
%%%                        |______________________________________| 


