%%% This output was generated by the following command:
%%% candc/bin/boxer --stdin --box true --resolve true --instantiate true --roles proto 

:- multifile     sem/3, id/2.
:- discontiguous sem/3, id/2.
:- dynamic       sem/3, id/2.
%%% Where was Tom Cruise born ? 
id(1,1).
sem(1,
	[
		1001:[tok:'Where',pos:'WRB',lemma:where,namex:'O'],
		1002:[tok:was,pos:'VBD',lemma:be,namex:'O'],
		1003:[tok:'Tom',pos:'NNP',lemma:'Tom',namex:'I-ORG'],
		1004:[tok:'Cruise',pos:'NNP',lemma:'Cruise',namex:'I-ORG'],
		1005:[tok:born,pos:'VBN',lemma:bear,namex:'O'],
		1006:[tok: ?,pos:'.',lemma: ?,namex:'O']
	],
	alfa(
		top,
		drs(
			[[]:x0],
			[
				[1003,1004]:named(x0,tom_cruise,org,0)
			]
		),
		drs(
			[],
			[
				[]:whq(
					[loc:any],
					drs(
						[[]:x1],
						[
							[1001]:pred(x1,location,n,1)
						]
					),
					x1,
					drs(
						[[]:x2],
						[
							[]:rel(x2,x1,loc_rel,0),
							[]:rel(x2,x0,patient,0),
							[1005]:pred(x2,bear,v,0)
						]
					)
				)
			]
		)
	)
).
%%%   ________________________   _________________________________  
%%%  |x0                      | |                                 | 
%%%  |........................| |.................................| 
%%% (|named(x0,tom_cruise,org)|A|  ____________   ______________  |)
%%%  |________________________| | |x1          | |x2            | | 
%%%                             | |............| |..............| | 
%%%                             | |location(x1)|?|loc_rel(x2,x1)| | 
%%%                             | |____________| |patient(x2,x0)| | 
%%%                             |                |bear(x2)      | | 
%%%                             |                |______________| | 
%%%                             |_________________________________| 


