%%% This output was generated by the following command:
%%% candc/bin/boxer --stdin --box true --resolve true --instantiate true --roles proto 

:- multifile     sem/3, id/2.
:- discontiguous sem/3, id/2.
:- dynamic       sem/3, id/2.
%%% Which rivers do not flow through France ? 
id(1,1).
sem(1,
	[
		1001:[tok:'Which',pos:'WDT',lemma:which,namex:'O'],
		1002:[tok:rivers,pos:'NNS',lemma:river,namex:'O'],
		1003:[tok:do,pos:'VBP',lemma:do,namex:'O'],
		1004:[tok:not,pos:'RB',lemma:not,namex:'O'],
		1005:[tok:flow,pos:'VB',lemma:flow,namex:'O'],
		1006:[tok:through,pos:'IN',lemma:through,namex:'O'],
		1007:[tok:'France',pos:'NNP',lemma:'France',namex:'I-LOC'],
		1008:[tok: ?,pos:'.',lemma: ?,namex:'O']
	],
	alfa(
		top,
		drs(
			[[]:x0],
			[
				[1007]:named(x0,france,loc,0)
			]
		),
		drs(
			[],
			[
				[1004]:not(
					drs(
						[],
						[
							[]:whq(
								[],
								drs(
									[[1001]:x1],
									[
										[1002]:pred(x1,river,n,0)
									]
								),
								x1,
								drs(
									[[]:x2],
									[
										[]:rel(x2,x1,agent,0),
										[1005]:pred(x2,flow,v,0),
										[1006]:rel(x2,x0,through,0)
									]
								)
							)
						]
					)
				)
			]
		)
	)
).

%%%   ____________________   ____________________________________  
%%%  |x0                  | |                                    | 
%%%  |....................| |....................................| 
%%% (|named(x0,france,loc)|A|     ______________________________ |)
%%%  |____________________| |    |                              || 
%%%                         |  ¬ |..............................|| 
%%%                         |    |  _________   ______________  || 
%%%                         |    | |x1       | |x2            | || 
%%%                         |    | |.........| |..............| || 
%%%                         |    | |river(x1)|?|agent(x2,x1)  | || 
%%%                         |    | |_________| |flow(x2)      | || 
%%%                         |    |             |through(x2,x0)| || 
%%%                         |    |             |______________| || 
%%%                         |    |______________________________|| 
%%%                         |____________________________________| 


