%%% This output was generated by the following command:
%%% candc/bin/boxer --stdin --box true --resolve true --instantiate true --roles proto 

:- multifile     sem/3, id/2.
:- discontiguous sem/3, id/2.
:- dynamic       sem/3, id/2.
%%% Which rivers flow through France ? 
id(1,1).
sem(1,
	[
		1001:[tok:'Which',pos:'WDT',lemma:which,namex:'O'],
		1002:[tok:rivers,pos:'NNS',lemma:river,namex:'O'],
		1003:[tok:flow,pos:'VBP',lemma:flow,namex:'O'],
		1004:[tok:through,pos:'IN',lemma:through,namex:'O'],
		1005:[tok:'France',pos:'NNP',lemma:'France',namex:'I-LOC'],
		1006:[tok: ?,pos:'.',lemma: ?,namex:'O']
	],
	alfa(
		top,
		drs(
			[[]:x0],
			[
				[1005]:named(x0,france,loc,0)
			]
		),
		drs(
			[],
			[
				[]:whq(
					[],
					drs(
						[[1001]:x1],
						[
							[1002]:pred(x1,river,n,0)
						]
					),
					x1,
					drs(
						[[]:x2],
						[
							[]:rel(x2,x1,agent,0),
							[1003]:pred(x2,flow,v,0),
							[1004]:rel(x2,x0,through,0)
						]
					)
				)
			]
		)
	)
).

%%%   ____________________   ______________________________  
%%%  |x0                  | |                              | 
%%%  |....................| |..............................| 
%%% (|named(x0,france,loc)|A|  _________   ______________  |)
%%%  |____________________| | |x1       | |x2            | | 
%%%                         | |.........| |..............| | 
%%%                         | |river(x1)|?|agent(x2,x1)  | | 
%%%                         | |_________| |flow(x2)      | | 
%%%                         |             |through(x2,x0)| | 
%%%                         |             |______________| | 
%%%                         |______________________________| 


