%%% This output was generated by the following command:
%%% candc/bin/boxer --stdin --box true --resolve true --instantiate true 

:- multifile     sem/3, id/2.
:- discontiguous sem/3, id/2.
:- dynamic       sem/3, id/2.
%%% Who is the author of The Great Gatsby ? 
id(1,1).
sem(1,
	[
		1001:[tok:'Who',pos:'WP',lemma:who,namex:'O'],
		1002:[tok: (is),pos:'VBZ',lemma:be,namex:'O'],
		1003:[tok:the,pos:'DT',lemma:the,namex:'O'],
		1004:[tok:author,pos:'NN',lemma:author,namex:'O'],
		1005:[tok:of,pos:'IN',lemma:of,namex:'O'],
		1006:[tok:'The',pos:'DT',lemma:the,namex:'I-ORG'],
		1007:[tok:'Great',pos:'NNP',lemma:'Great',namex:'I-ORG'],
		1008:[tok:'Gatsby',pos:'NNP',lemma:'Gatsby',namex:'I-ORG'],
		1009:[tok: ?,pos:'.',lemma: ?,namex:'O']
	],
	alfa(
		top,
		drs(
			[[1003]:x0,[1006]:x1],
			[
				[1004]:pred(x0,author,n,0),
				[1007,1008]:named(x1,great_gatsby,org,0)
			]
		),
		drs(
			[],
			[
				[]:whq(
					[ins:hum],
					drs(
						[[]:x2],
						[
							[1001]:pred(x2,person,n,1)
						]
					),
					x2,
					drs(
						[[]:x3],
						[
							[]:prop(
								x3,
								drs(
									[],
									[
										[1002]:eq(x2,x0),
										[1005]:rel(x0,x1,of,0)
									]
								)
							)
						]
					)
				)
			]
		)
	)
).
%%%   __________________________   ________________________________  
%%%  |x0 x1                     | |                                | 
%%%  |..........................| |................................| 
%%% (|author(x0)                |A|  __________   _______________  |)
%%%  |named(x1,great_gatsby,org)| | |x2        | |x3             | | 
%%%  |__________________________| | |..........| |...............| | 
%%%                               | |person(x2)|?|     _________ | | 
%%%                               | |__________| |    |         || | 
%%%                               |              | x3:|.........|| | 
%%%                               |              |    |x2 = x0  || | 
%%%                               |              |    |of(x0,x1)|| | 
%%%                               |              |    |_________|| | 
%%%                               |              |_______________| | 
%%%                               |________________________________| 


