%%% This output was generated by the following command:
%%% candc/bin/boxer --stdin --box true --resolve true --instantiate true --roles proto 

:- multifile     sem/3, id/2.
:- discontiguous sem/3, id/2.
:- dynamic       sem/3, id/2.
%%% Who is the prime minister of the UK ? 
id(1,1).
sem(1,
	[
		1001:[tok:'Who',pos:'WP',lemma:who,namex:'O'],
		1002:[tok: (is),pos:'VBZ',lemma:be,namex:'O'],
		1003:[tok:the,pos:'DT',lemma:the,namex:'O'],
		1004:[tok:prime,pos:'JJ',lemma:prime,namex:'O'],
		1005:[tok:minister,pos:'NN',lemma:minister,namex:'O'],
		1006:[tok:of,pos:'IN',lemma:of,namex:'O'],
		1007:[tok:the,pos:'DT',lemma:the,namex:'O'],
		1008:[tok:'UK',pos:'NNP',lemma:'UK',namex:'I-ORG'],
		1009:[tok: ?,pos:'.',lemma: ?,namex:'O']
	],
	alfa(
		top,
		drs(
			[[1003]:x0,[1007]:x1],
			[
				[1005]:pred(x0,minister,n,0),
				[1004]:pred(x0,prime,a,0),
				[1008]:named(x1,uk,org,0)
			]
		),
		drs(
			[],
			[
				[]:whq(
					[ins:hum],
					drs(
						[[]:x2],
						[
							[1001]:pred(x2,person,n,1)
						]
					),
					x2,
					drs(
						[[]:x3],
						[
							[]:prop(
								x3,
								drs(
									[],
									[
										[1002]:eq(x2,x0),
										[1006]:rel(x0,x1,of,0)
									]
								)
							)
						]
					)
				)
			]
		)
	)
).
%%%   ________________   ________________________________  
%%%  |x0 x1           | |                                | 
%%%  |................| |................................| 
%%% (|minister(x0)    |A|  __________   _______________  |)
%%%  |prime(x0)       | | |x2        | |x3             | | 
%%%  |named(x1,uk,org)| | |..........| |...............| | 
%%%  |________________| | |person(x2)|?|     _________ | | 
%%%                     | |__________| |    |         || | 
%%%                     |              | x3:|.........|| | 
%%%                     |              |    |x2 = x0  || | 
%%%                     |              |    |of(x0,x1)|| | 
%%%                     |              |    |_________|| | 
%%%                     |              |_______________| | 
%%%                     |________________________________| 


